### ISSUE TITLE
Restrict Firestore access

### ISSUE THREAD

**Issue by timowevel1** [achmadqomarudin/MeetingApp#1]
Hey there,

first: thank you for this amazing and useful application!

When I went through the firestore configuration I noticed that you use the test mode to make database read & write possible. Is there a possibility that you can make the database more safe so it cant get hijacked?

Thanks!

Greets Timo

**Comment by achmadqomarudin** [comment]
Hi bro, maybe you can read at this documentation about [Firestore Security](https://firebase.google.com/docs/firestore/security/overview) to make more secure configuration. 

I hope it can help you bro :)

**Comment by timowevel1** [comment]
Hey, thanks for your answer. Could you maybe make an example? Because when I restrict the access then the client is not working anymore because it has no permissions anymore to check for the requested user account.
